### ISSUE TITLE
No TensorFlow for Python 2.7

### ISSUE THREAD

**Issue by SoftAvocado** [gsurma/slitherin#2]
It seems Tensorflow doesn't support Python 2.7 anymore. I installed some of the versions (1.10.0, 1.5.0, 1.8.0) with .whl from here https://github.com/fo40225/tensorflow-windows-wheel. But with all versions im having this error:

C:\test\slitherin>python slitherin.py --help
pygame 2.0.1 (SDL 2.0.14, Python 2.7.17)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "slitherin.py", line 11, in <module>
    from game.models.domain_specific.dnn_ai_solver import DNNSolver, DNNTrainer
  File "C:\test\slitherin\game\models\domain_specific\dnn_ai_solver.py", line 7, in <module>
    from tf_models.dnn_model import DeepNeuralNetModel
  File "C:\test\slitherin\tf_models\dnn_model.py", line 2, in <module>
    import tflearn
  File "C:\Users\kotich\AppData\Local\Programs\Python\Python27\lib\site-packages\tflearn\__init__.py", line 4, in <module>
    import tensorflow.compat.v1 as tf
ImportError: No module named v1

Any suggestions on what's wrong and how i can launch your code?

**Comment by JacobLiu001** [comment]
This is caused by tflearn updating to drop support for TF1. 
Consider Downgrading to tflearn==0.3.2
Also, you need to downgrade Keras to 2.2.5, as newer Keras versions started dropping support for TF1.

EDIT: More Detailed instructions:
you can do 
`pip uninstall package-name`
then run
`pip install package-name==desired-version` (e.g. `pip install tflearn==0.3.2`)
(or just get `requirements.txt` from my fork and running `pip install -r requirements.txt` again)
